import json

tools_list = [
    # Chatbots
    ("ChatGPT", "https://chat.openai.com/", "Chatbots"),
    ("Gemini", "https://gemini.google.com/", "Chatbots"),
    ("Claude", "https://claude.ai/", "Chatbots"),
    ("Perplexity", "https://www.perplexity.ai/", "Chatbots"),
    ("Character.ai", "https://character.ai/", "Chatbots"),
    ("Pi", "https://pi.ai/", "Chatbots"),
    ("Poe", "https://poe.com/", "Chatbots"),
    ("HuggingChat", "https://huggingface.co/chat", "Chatbots"),
    ("Meta AI", "https://ai.meta.com/", "Chatbots"),
    ("Grok", "https://x.ai/", "Chatbots"),
    ("You.com", "https://you.com/", "Chatbots"),
    ("Kuki", "https://www.kuki.ai/", "Chatbots"),
    ("Replika", "https://replika.com/", "Chatbots"),
    ("Chai", "https://chai-research.com/", "Chatbots"),
    ("DeepSeek", "https://chat.deepseek.com/", "Chatbots"),
    ("Janitor AI", "https://janitorai.com/", "Chatbots"),
    ("ChatPDF", "https://www.chatpdf.com/", "Chatbots"),
    ("Chatsonic", "https://writesonic.com/chat", "Chatbots"),
    ("Bing Chat", "https://www.bing.com/chat", "Chatbots"),
    ("Andi", "https://andisearch.com/", "Chatbots"),
    
    # Image
    ("Midjourney", "https://www.midjourney.com/", "Image"),
    ("DALL-E 3", "https://openai.com/dall-e-3", "Image"),
    ("Stable Diffusion", "https://stability.ai/", "Image"),
    ("Leonardo.ai", "https://leonardo.ai/", "Image"),
    ("Playground AI", "https://playgroundai.com/", "Image"),
    ("Ideogram", "https://ideogram.ai/", "Image"),
    ("Krea", "https://www.krea.ai/", "Image"),
    ("Magnific", "https://magnific.ai/", "Image"),
    ("Topaz Labs", "https://www.topazlabs.com/", "Image"),
    ("Adobe Firefly", "https://firefly.adobe.com/", "Image"),
    ("Luma Genie", "https://lumalabs.ai/genie", "Image"),
    ("Meshy", "https://www.meshy.ai/", "Image"),
    ("Tripo3D", "https://www.tripo3d.ai/", "Image"),
    ("CSM", "https://csm.ai/", "Image"),
    ("Lexica", "https://lexica.art/", "Image"),
    ("Civitai", "https://civitai.com/", "Image"),
    ("NightCafe", "https://creator.nightcafe.studio/", "Image"),
    ("Artbreeder", "https://www.artbreeder.com/", "Image"),
    ("SeaArt", "https://seaart.ai/", "Image"),
    ("Recraft", "https://www.recraft.ai/", "Image"),
    ("Stockimg.ai", "https://stockimg.ai/", "Image"),
    ("Pebblely", "https://pebblely.com/", "Image"),
    ("Photoroom", "https://www.photoroom.com/", "Image"),
    ("Clipdrop", "https://clipdrop.co/", "Image"),
    ("Craiyon", "https://www.craiyon.com/", "Image"),
    ("Cutout.pro", "https://www.cutout.pro/", "Image"),
    ("Kaiber", "https://kaiber.ai/", "Image"),
    ("Tengr.ai", "https://tengr.ai/", "Image"),
    ("DeepAI", "https://deepai.org/", "Image"),
    ("Dezgo", "https://dezgo.com/", "Image"),

    # Video
    ("Runway", "https://runwayml.com/", "Video"),
    ("Pika Labs", "https://pika.art/", "Video"),
    ("Sora", "https://openai.com/sora", "Video"),
    ("Descript", "https://www.descript.com/", "Video"),
    ("Synthesia", "https://www.synthesia.io/", "Video"),
    ("HeyGen", "https://www.heygen.com/", "Video"),
    ("CapCut", "https://www.capcut.com/", "Video"),
    ("InVideo", "https://invideo.io/", "Video"),
    ("Opus Clip", "https://www.opus.pro/", "Video"),
    ("Munch", "https://www.getmunch.com/", "Video"),
    ("Veed.io", "https://www.veed.io/", "Video"),
    ("Luma Dream Machine", "https://lumalabs.ai/dream-machine", "Video"),
    ("Kling AI", "https://klingai.com/", "Video"),
    ("Haiper", "https://haiper.ai/", "Video"),
    ("Rask AI", "https://www.rask.ai/", "Video"),
    ("Klap", "https://klap.app/", "Video"),
    ("Submagic", "https://submagic.co/", "Video"),
    ("Vizard", "https://vizard.ai/", "Video"),
    ("Fliki", "https://fliki.ai/", "Video"),
    ("Pictory", "https://pictory.ai/", "Video"),
    ("D-ID", "https://www.d-id.com/", "Video"),
    ("Colossyan", "https://www.colossyan.com/", "Video"),
    ("Elai.io", "https://elai.io/", "Video"),
    ("Hour One", "https://hourone.ai/", "Video"),
    ("Wonder Studio", "https://wonderdynamics.com/", "Video"),
    ("GliaCloud", "https://www.gliacloud.com/", "Video"),
    ("Wisecut", "https://www.wisecut.video/", "Video"),
    ("Gling", "https://gling.ai/", "Video"),
    ("Vidyo.ai", "https://vidyo.ai/", "Video"),
    ("Maja", "https://maja.ai/", "Video"),

    # Audio
    ("ElevenLabs", "https://elevenlabs.io/", "Audio"),
    ("Suno", "https://suno.com/", "Audio"),
    ("Udio", "https://www.udio.com/", "Audio"),
    ("Murf.ai", "https://murf.ai/", "Audio"),
    ("Lovo.ai", "https://lovo.ai/", "Audio"),
    ("ElevenLabs Dubbing", "https://elevenlabs.io/dubbing", "Audio"),
    ("WellSaid Labs", "https://wellsaidlabs.com/", "Audio"),
    ("Play.ht", "https://play.ht/", "Audio"),
    ("Resemble AI", "https://www.resemble.ai/", "Audio"),
    ("Altered", "https://www.altered.ai/", "Audio"),
    ("Voiceify", "https://voiceify.ai/", "Audio"),
    ("Soundraw", "https://soundraw.io/", "Audio"),
    ("Mubert", "https://mubert.com/", "Audio"),
    ("Boomy", "https://boomy.com/", "Audio"),
    ("AIVA", "https://www.aiva.ai/", "Audio"),
    ("Splash", "https://www.splashmusic.com/", "Audio"),
    ("Beatoven.ai", "https://www.beatoven.ai/", "Audio"),
    ("Audiocraft", "https://audiocraft.metademolab.com/", "Audio"),
    ("Vocal Remover", "https://vocalremover.org/", "Audio"),
    ("LALAL.AI", "https://www.lalal.ai/", "Audio"),

    # Coding
    ("GitHub Copilot", "https://github.com/features/copilot", "Coding"),
    ("Cursor", "https://cursor.com/", "Coding"),
    ("Replit", "https://replit.com/", "Coding"),
    ("Hugging Face", "https://huggingface.co/", "Coding"),
    ("LangChain", "https://www.langchain.com/", "Coding"),
    ("Pinecone", "https://www.pinecone.io/", "Coding"),
    ("Vercel v0", "https://v0.dev/", "Coding"),
    ("Codeium", "https://codeium.com/", "Coding"),
    ("Tabnine", "https://www.tabnine.com/", "Coding"),
    ("Cohere", "https://cohere.com/", "Coding"),
    ("Mistral", "https://mistral.ai/", "Coding"),
    ("CodiumAI", "https://www.codium.ai/", "Coding"),
    ("Blackbox AI", "https://www.blackbox.ai/", "Coding"),
    ("Sourcegraph Cody", "https://about.sourcegraph.com/cody", "Coding"),
    ("MutableAI", "https://mutable.ai/", "Coding"),
    ("Warp", "https://www.warp.dev/", "Coding"),
    ("Mintlify", "https://mintlify.com/", "Coding"),
    ("Qdrant", "https://qdrant.tech/", "Coding"),
    ("Weaviate", "https://weaviate.io/", "Coding"),
    ("Chroma", "https://www.trychroma.com/", "Coding"),
    ("LlamaIndex", "https://www.llamaindex.ai/", "Coding"),
    ("Supabase", "https://supabase.com/", "Coding"),
    ("Firebase Genkit", "https://firebase.google.com/products/genkit", "Coding"),
    ("Ollama", "https://ollama.com/", "Coding"),
    ("LM Studio", "https://lmstudio.ai/", "Coding"),
    ("Anyscale", "https://www.anyscale.com/", "Coding"),
    ("Together AI", "https://www.together.ai/", "Coding"),
    ("Fireworks AI", "https://fireworks.ai/", "Coding"),
    ("Groq", "https://groq.com/", "Coding"),
    ("Modal", "https://modal.com/", "Coding"),

    # Productivity
    ("Notion AI", "https://www.notion.so/product/ai", "Productivity"),
    ("Beautiful.ai", "https://www.beautiful.ai/", "Productivity"),
    ("Gamma", "https://gamma.app/", "Productivity"),
    ("Tome", "https://tome.app/", "Productivity"),
    ("Miro AI", "https://miro.com/ai/", "Productivity"),
    ("Otter.ai", "https://otter.ai/", "Productivity"),
    ("Fireflies.ai", "https://fireflies.ai/", "Productivity"),
    ("Bardeen", "https://www.bardeen.ai/", "Productivity"),
    ("Zapier AI", "https://zapier.com/ai", "Productivity"),
    ("Make", "https://www.make.com/", "Productivity"),
    ("Taskade", "https://www.taskade.com/", "Productivity"),
    ("Superhuman", "https://superhuman.com/", "Productivity"),
    ("Shortwave", "https://www.shortwave.com/", "Productivity"),
    ("Mem", "https://mem.ai/", "Productivity"),
    ("Reflect", "https://reflect.app/", "Productivity"),
    ("Sana", "https://sanalabs.com/", "Productivity"),
    ("Motion", "https://www.usemotion.com/", "Productivity"),
    ("Reclaim", "https://reclaim.ai/", "Productivity"),
    ("Clockwise", "https://www.getclockwise.com/", "Productivity"),
    ("Trevor AI", "https://trevorai.com/", "Productivity"),
    ("Akiflow", "https://akiflow.com/", "Productivity"),
    ("Sunsama", "https://sunsama.com/", "Productivity"),
    ("Fathom", "https://fathom.video/", "Productivity"),
    ("Read AI", "https://www.read.ai/", "Productivity"),
    ("Krisp", "https://krisp.ai/", "Productivity"),
    ("Glean", "https://www.glean.com/", "Productivity"),
    ("Dashworks", "https://www.dashworks.ai/", "Productivity"),
    ("Slite", "https://slite.com/", "Productivity"),
    ("Coda AI", "https://coda.io/product/ai", "Productivity"),
    ("Airtable AI", "https://airtable.com/platform/ai", "Productivity"),

    # Marketing & Writing
    ("Grammarly", "https://www.grammarly.com/", "Marketing"),
    ("Jasper", "https://www.jasper.ai/", "Marketing"),
    ("Copy.ai", "https://www.copy.ai/", "Marketing"),
    ("Writesonic", "https://writesonic.com/", "Marketing"),
    ("Rytr", "https://rytr.me/", "Marketing"),
    ("Anyword", "https://anyword.com/", "Marketing"),
    ("Surfer SEO", "https://surferseo.com/", "Marketing"),
    ("Frase", "https://www.frase.io/", "Marketing"),
    ("Clearscope", "https://www.clearscope.io/", "Marketing"),
    ("MarketMuse", "https://www.marketmuse.com/", "Marketing"),
    ("Sudowrite", "https://www.sudowrite.com/", "Marketing"),
    ("NovelAI", "https://novelai.net/", "Marketing"),
    ("Wordtune", "https://www.wordtune.com/", "Marketing"),
    ("QuillBot", "https://quillbot.com/", "Marketing"),
    ("ProWritingAid", "https://prowritingaid.com/", "Marketing"),
    ("Hemingway Editor", "https://hemingwayapp.com/", "Marketing"),
    ("Lex", "https://lex.page/", "Marketing"),
    ("Hootsuite OwlyWriter", "https://www.hootsuite.com/features/owlywriter-ai", "Marketing"),
    ("Lately", "https://www.lately.ai/", "Marketing"),
    ("Taplio", "https://taplio.com/", "Marketing"),

    # Design
    ("Canva Magic Studio", "https://www.canva.com/magic/", "Design"),
    ("Figma AI", "https://www.figma.com/ai/", "Design"),
    ("Uizard", "https://uizard.io/", "Design"),
    ("Galileo AI", "https://www.usegalileo.ai/", "Design"),
    ("Relume", "https://www.relume.io/", "Design"),
    ("Webflow AI", "https://webflow.com/ai", "Design"),
    ("Framer AI", "https://www.framer.com/ai/", "Design"),
    ("Dora", "https://dora.run/", "Design"),
    ("Spline", "https://spline.design/", "Design"),
    ("Looka", "https://looka.com/", "Design"),
    ("Brandmark", "https://brandmark.io/", "Design"),
    ("Khroma", "https://www.khroma.co/", "Design"),
    ("Huemint", "https://huemint.com/", "Design"),
    ("Colormagic", "https://colormagic.app/", "Design"),
    ("Fontjoy", "https://fontjoy.com/", "Design"),
    ("Autodraw", "https://www.autodraw.com/", "Design"),
    ("Magician", "https://magician.design/", "Design"),
    ("Genius", "https://genius.design/", "Design"),
    ("Viesus", "https://www.viesus.com/", "Design"),
    ("Fronty", "https://fronty.com/", "Design"),

    # Research
    ("Phind", "https://www.phind.com/", "Research"),
    ("Consensus", "https://consensus.app/", "Research"),
    ("Elicit", "https://elicit.com/", "Research"),
    ("Scite", "https://scite.ai/", "Research"),
    ("Arc Search", "https://arc.net/", "Research"),
    ("Anthropic", "https://www.anthropic.com/", "Research"),
    ("Perplexity Pages", "https://www.perplexity.ai/pages", "Research"),
    ("Google Scholar AI", "https://scholar.google.com/", "Research"),
    ("Semantic Scholar", "https://www.semanticscholar.org/", "Research"),
    ("Brave Search AI", "https://search.brave.com/", "Research"),
    ("YouChat", "https://you.com/search", "Research"),
    ("Komo Search", "https://komo.ai/", "Research"),
    ("Mendel3", "https://www.mendel3.com/", "Research"),
    ("SciSpace", "https://typeset.io/", "Research"),
    ("Iris.ai", "https://iris.ai/", "Research"),
    ("ResearchRabbit", "https://www.researchrabbit.ai/", "Research"),
    ("Scholarcy", "https://www.scholarcy.com/", "Research"),
    ("ChatDoc", "https://chatdoc.com/", "Research"),
    ("Humata", "https://www.humata.ai/", "Research"),
    ("Genei", "https://www.genei.io/", "Research")
]

# Write exact 200 items to data.js
bookmarks = []
for title, url, category in tools_list[:200]:
    bookmarks.append({
        "title": title,
        "url": url,
        "category": category
    })

with open("data.js", "w", encoding="utf-8") as f:
    f.write("const bookmarksData = " + json.dumps(bookmarks, indent=2) + ";\n")

print(f"Generated {len(bookmarks)} REAL tools in data.js")
